In [1]:
# 데이터 프레임 만들기
import pandas as pd

food = pd.DataFrame({
    "메뉴": ["김밥", "비빔밥", "자장면", "우동", "김밥", "자장면", "김밥"],
    "가격": [3000, 7000, 5500, 5500, 3500, 6000, 4000],
    "분류": ["한식", "한식", "중식", "일식", "한식", "중식", "한식"]
})
food

food.to_csv("datas/food.csv", index=False)

df = pd.read_csv("datas/food.csv")
df

    메뉴    가격  분류
0   김밥  3000  한식
1  비빔밥  7000  한식
2  자장면  5500  중식
3   우동  5500  일식
4   김밥  3500  한식
5  자장면  6000  중식
6   김밥  4000  한식

In [2]:
df.head()
df.tail()
df.info()

df.value_counts()
df["메뉴"].value_counts()
df["분류"].value_counts()

df.describe()
df.describe(include='object')
# df.describe(include='number')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   분류      7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

        메뉴  분류
count    7   7
unique   4   3
top     김밥  한식
freq     3   4

In [3]:
# 칼럼 추가
discount = 0.1
df["할인가"] = df["가격"] * (1 - discount)
df
df.info()
   
# 자료형 변환 - astype()
df["할인가"] = df["할인가"].astype("int64")
df
# df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   분류      7 non-null      object
 3   할인가     7 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 356.0+ bytes

    메뉴    가격  분류   할인가
0   김밥  3000  한식  2700
1  비빔밥  7000  한식  6300
2  자장면  5500  중식  4950
3   우동  5500  일식  4950
4   김밥  3500  한식  3150
5  자장면  6000  중식  5400
6   김밥  4000  한식  3600

In [4]:
# 조건 검색
result1 = (df["메뉴"] == "자장면")
result1
df[result1]

result4 = (df["메뉴"] == "자장면") & (df["가격"] >= 6000)
df[result4]

    메뉴    가격  분류   할인가
5  자장면  6000  중식  5400

In [5]:
# 정렬
df.sort_values("가격", ascending=False)

    메뉴    가격  분류   할인가
1  비빔밥  7000  한식  6300
5  자장면  6000  중식  5400
2  자장면  5500  중식  4950
3   우동  5500  일식  4950
6   김밥  4000  한식  3600
4   김밥  3500  한식  3150
0   김밥  3000  한식  2700

In [6]:
# 판다스의 통계, 수학 함수
df["가격"].count()
df["가격"].sum()
round(df["가격"].mean(), 2)
df["가격"].var()
df["가격"].std()
df["가격"].min()
df["가격"].idxmax()

df["가격"].quantile(.25)
df["가격"].quantile(.50)

result = df["가격"] < df["가격"].quantile(.25)
print(df[result])

df["가격"].mode()[0]

   메뉴    가격  분류   할인가
0  김밥  3000  한식  2700
4  김밥  3500  한식  3150

5500

In [7]:
import pandas as pd

# "수량" 칼럼 추가
df["수량"] = [10, 10, 15, 5, 7, 7, 8]
df

# csv 파일로 변환
df.to_csv("./datas/food2.csv", index=False)

# csv 파일 읽기
food = pd.read_csv("./datas/food2.csv")
food

    메뉴    가격  분류   할인가  수량
0   김밥  3000  한식  2700  10
1  비빔밥  7000  한식  6300  10
2  자장면  5500  중식  4950  15
3   우동  5500  일식  4950   5
4   김밥  3500  한식  3150   7
5  자장면  6000  중식  5400   7
6   김밥  4000  한식  3600   8

In [8]:
# 그룹핑 - groupby()
df["분류"].value_counts()

food.groupby("메뉴").mean(numeric_only=True)
food.groupby("분류").mean(numeric_only=True)

food.groupby("분류")["가격"].mean()
food.groupby("분류")["수량"].mean()

분류
일식     5.00
중식    11.00
한식     8.75
Name: 수량, dtype: float64