In [1]:
# 데이터 프레임 직접 생성
import pandas as pd

data = [
    ['키보드', 20000],
    ['마우스', 32000],
    ['USB 메모리', 11000]
]

df = pd.DataFrame(data, columns=['name', 'price'])
df

df['name']
df[['name', 'price']]

      name  price
0      키보드  20000
1      마우스  32000
2  USB 메모리  11000

In [20]:
import pandas as pd

df = pd.DataFrame({
    "name": ['키보드', '마우스', 'USB 메모리'],
    "price": [20000, 32000, 11000]
})

# 칼럼 추가
df['spec'] = ['유선', '무선', '128GB']

df['할인가'] = df['price'] * 0.8
df

# 수정후 반드시 df에 다시 저장.
df = df.rename(columns={"name": "품명", "price":"가격", "spec":"제품상세"})
df

#### CSV 파일이란?
##### 쉼표(,)로 데이터를 구분하여 저장하는 텍스트 파일 형식이다.

In [21]:
import pandas as pd

# csv 파일 만들기 - index 제외
df.to_csv("datas/computer.csv", index=False)

# csv 파일 읽기
computer = pd.read_csv("datas/computer.csv")
computer

        품명     가격   제품상세      할인가
0      키보드  20000     유선  16000.0
1      마우스  32000     무선  25600.0
2  USB 메모리  11000  128GB   8800.0

In [26]:
# 행 선택 - loc[행(행이름)]
# print(df)

print(df.loc[0])
print(df.loc[0:1])
print("========================================")

# 행과 열 선택 - loc[행이름, 열(칼럼명)]
print(df.loc[0, "품명"])
print(df.loc[1, "가격"])
print(df.loc[0:1, "품명"])
print(df.loc[0:1, ["품명", "가격"]])

품명          키보드
가격        20000
제품상세         유선
할인가     16000.0
Name: 0, dtype: object
    품명     가격 제품상세      할인가
0  키보드  20000   유선  16000.0
1  마우스  32000   무선  25600.0
========================================
키보드
32000
0    키보드
1    마우스
Name: 품명, dtype: object
    품명     가격
0  키보드  20000
1  마우스  32000

In [36]:
# 행 선택 - iloc[행(인덱스번호)]
# print(df)

print(df.iloc[0])
print(df.iloc[0:2]) # 끝인덱스-1
print("========================================")

# 행과 열 선택 - loc[행(인덱스번호), 열(인덱스번호)]
print(df.iloc[0, 0])
print(df.iloc[1, 1])
print(df.iloc[0:2, 0])
print(df.iloc[0:2, 0:2])

품명          키보드
가격        20000
제품상세         유선
할인가     16000.0
Name: 0, dtype: object
    품명     가격 제품상세      할인가
0  키보드  20000   유선  16000.0
1  마우스  32000   무선  25600.0
========================================
키보드
32000
0    키보드
1    마우스
Name: 품명, dtype: object
    품명     가격
0  키보드  20000
1  마우스  32000

In [19]:
# 요소값 변경 및 추가
df2 = df.copy() #원본 유지 복사
df2

# 품명 '마우스'를 '무선마우스'로 변경
df2.loc[1, "품명"] = "무선마우스"
# 무선 마우스의 가격을 35000으로 변경
df2.loc[1, "가격"] = 35000
# 무선 마우스의 할인가 수정
df2.loc[1, "할인가"] = df2.loc[1, "가격"] * 0.8
df2

# 행 추가
df2.loc[3] = ["키보드", 40000, "무선", 0.0]
df2.loc[3, "할인가"] = df2.loc[3, "가격"] * 0.8
df2

        품명     가격   제품상세      할인가
0      키보드  20000     유선  16000.0
1    무선마우스  35000     무선  28000.0
2  USB 메모리  11000  128GB   8800.0
3      키보드  40000     무선  32000.0

In [38]:
# 행 삭제 - drop(행번호, axis=0)
# 열 삭제 - drop(칼럼명, axis=1)
df3 = df2.copy()
df3

# 3행 삭제
df3 = df3.drop(3, axis=0)
df3

# 열 삭제
# df3 = df3.drop("할인가", axis=1)
df3 = df3.drop(["제품상세", "할인가"], axis=1)
df3

        품명     가격
0      키보드  20000
1    무선마우스  35000
2  USB 메모리  11000

In [44]:
# 인덱스 설정 - set_index(칼럼명)
df4 = df.copy()
df4

df4 = df4.set_index("품명")
df4

# 행, 열 선택 - loc[ ]
print(df4.loc["키보드"])
print(df4.loc[["키보드", "마우스"]])
print(df4.loc["키보드":"USB 메모리"])
print("========================================")

# 행, 열 선택 - iloc[ ]
print(df4.iloc[0])
print(df4.iloc[0:2])
print(df4.iloc[0:3])

가격        20000
제품상세         유선
할인가     16000.0
Name: 키보드, dtype: object
        가격 제품상세      할인가
품명
키보드  20000   유선  16000.0
마우스  32000   무선  25600.0
            가격   제품상세      할인가
품명
키보드      20000     유선  16000.0
마우스      32000     무선  25600.0
USB 메모리  11000  128GB   8800.0
========================================
가격        20000
제품상세         유선
할인가     16000.0
Name: 키보드, dtype: object
        가격 제품상세      할인가
품명
키보드  20000   유선  16000.0
마우스  32000   무선  25600.0
            가격   제품상세      할인가
품명
키보드      20000     유선  16000.0
마우스      32000     무선  25600.0
USB 메모리  11000  128GB   8800.0

In [19]:
import pandas as pd

# csv 파일 만들기
df3.to_csv("datas/computer.csv", index=False)

# csv 파일 읽기
computer = pd.read_csv("datas/computer.csv")
computer

        품명     가격   제품상세      할인가   수량
0      키보드  20000     유선  16000.0  100
1      마우스  32000     무선  25600.0   50
2  USB 메모리  12000  128GB   9600.0  200
3      키보드  35000     무선  28000.0   50