In [7]:
# 데이터 프레임 만들기
import pandas as pd

food = pd.DataFrame({
    "메뉴": ["김밥", "비빔밥", "자장면", "우동", "김밥", "자장면", "김밥"],
    "가격": [3000, 7000, 5500, 5500, 3500, 6000, 4000],
    "분류": ["한식", "한식", "중식", "일식", "한식", "중식", "한식"]
})
food

food.to_csv("datas/food.csv", index=False)

df = pd.read_csv("datas/food.csv")
df

    메뉴    가격  분류
0   김밥  3000  한식
1  비빔밥  7000  한식
2  자장면  5500  중식
3   우동  5500  일식
4   김밥  3500  한식
5  자장면  6000  중식
6   김밥  4000  한식

In [12]:
df.head()
df.tail()
df.info()

df.value_counts()
df["메뉴"].value_counts()
df["분류"].value_counts()

df.describe()
df.describe(include='object')
# df.describe(include='number')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   분류      7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

        메뉴  분류
count    7   7
unique   4   3
top     김밥  한식
freq     3   4

In [ ]:
# 칼럼 추가

# 자료형 변환 - astype()

In [16]:
# 조건 검색
result1 = (df["메뉴"] == "자장면")
result1
df[result1]

result4 = (df["메뉴"] == "자장면") & (df["가격"] >= 6000)
df[result4]

    메뉴    가격  분류
5  자장면  6000  중식

In [19]:
# 정렬
df.sort_values("가격", ascending=False)

    메뉴    가격  분류
1  비빔밥  7000  한식
5  자장면  6000  중식
2  자장면  5500  중식
3   우동  5500  일식
6   김밥  4000  한식
4   김밥  3500  한식
0   김밥  3000  한식