In [2]:
# 데이터 프레임 직접 생성
import pandas as pd

data = [
    ['키보드', 20000],
    ['마우스', 32000],
    ['USB 메모리', 11000]
]

df = pd.DataFrame(data, columns=['name', 'price'])
df

df['name']
df[['name', 'price']]

      name  price
0      키보드  20000
1      마우스  32000
2  USB 메모리  11000

In [3]:
import pandas as pd

df = pd.DataFrame({
    "name": ['키보드', '마우스', 'USB 메모리'],
    "price": [20000, 32000, 11000]
})

# 칼럼 추가
df['spec'] = ['유선', '무선', '128GB']

df['할인가'] = df['price'] * 0.8
df

df = df.rename(columns={"name": "품명", "price":"가격", "spec":"제품상세"})
df

        품명     가격   제품상세      할인가
0      키보드  20000     유선  16000.0
1      마우스  32000     무선  25600.0
2  USB 메모리  11000  128GB   8800.0

In [4]:
# loc[행]
df.loc[0]
df.loc[1]
df.loc[0:1]
df.loc[[0, 1]]

# loc[행, 열]
df.loc[0, "품명"]
df.loc[1, "가격"]
df.loc[0:1, "품명"]
df.loc[0:1, ["품명", "가격"]]

    품명     가격
0  키보드  20000
1  마우스  32000

In [5]:
# iloc[행인덱스, 열인덱스]
df.iloc[0, 0]
df.iloc[1, 1]
df.iloc[0:2, 0]
df.iloc[0:2, 0:2]
# df.iloc[:, :]

    품명     가격
0  키보드  20000
1  마우스  32000

In [6]:
df2 = df.copy()
df2

df2 = df2.set_index("품명")
df2
df2.loc["키보드"]
df2.loc[["키보드", "마우스"]]
df2.loc["키보드":"USB 메모리"]

            가격   제품상세      할인가
품명
키보드      20000     유선  16000.0
마우스      32000     무선  25600.0
USB 메모리  11000  128GB   8800.0

In [11]:
df3 = df.copy()
df3

df3.loc[2, "가격"] = 12000
df3.loc[2, "할인가"] = df3.loc[2, "가격"] * 0.8
df3
df3['수량'] = [100, 50, 200]
df3
df3.loc[3] = ["키보드", 35000, "무선", 0.0, 50]
df3
df3.loc[3, "할인가"] = df3.loc[3, "가격"] * 0.8
df3

        품명     가격   제품상세      할인가   수량
0      키보드  20000     유선  16000.0  100
1      마우스  32000     무선  25600.0   50
2  USB 메모리  12000  128GB   9600.0  200
3      키보드  35000     무선  28000.0   50

In [15]:
# 행 삭제 - drop(행번호, axis), axis=0(행삭제), axis=1(열삭제)
df4 = df3.copy()
df4
df4 = df4.drop(3, axis=0)
df4

# 열 삭제
# df4 = df4.drop("할인가", axis=1)
df4
df4 = df4.drop(["할인가", "수량"], axis=1)
df4

        품명     가격   제품상세
0      키보드  20000     유선
1      마우스  32000     무선
2  USB 메모리  12000  128GB

In [19]:
import pandas as pd

# csv 파일 만들기
df3.to_csv("datas/computer.csv", index=False)

# csv 파일 읽기
computer = pd.read_csv("datas/computer.csv")
computer

        품명     가격   제품상세      할인가   수량
0      키보드  20000     유선  16000.0  100
1      마우스  32000     무선  25600.0   50
2  USB 메모리  12000  128GB   9600.0  200
3      키보드  35000     무선  28000.0   50